title: Loraine Menorca # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/lorainemnrc/">LinkedIn</a> |
  <a href="https://github.com/lorainemnrc">GitHub</a>
  </p>
  
  <p align="justify">
  Analytical and self-starter with 3 years of experience collaborating directly with Customer Experience and service, Product, Marketing, and Technology teams. Recent graduate of MS in Data Science program at the Asian Institute of Management.
  <br><br>
  With a proven track record of delivering over 15 impactful case studies utilizing Statistical and Machine Learning techniques in Python and R, along with creating 50+ dynamic dashboards in Tableau and Power BI. Adept at spearheading and successfully executing projects with minimal supervision.
  <br><br>
  </p>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
